apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storys
  template:
    metadata:
      labels:
        app: storys
    spec:
      containers:
        - name: story
          image: crawan/kube-data-volume
